# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bone}
  s.version = "0.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Delano Mandelbaum"]
  s.date = %q{2010-12-20}
  s.default_executable = %q{bone}
  s.description = %q{A simple store for remote environment variables}
  s.email = %q{delano@solutious.com}
  s.executables = ["bone"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.md"
  ]
  s.files = [
    "CHANGES.txt",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE.txt",
     "README.md",
     "Rakefile",
     "Rudyfile",
     "VERSION.yml",
     "bin/bone",
     "bone.gemspec",
     "config/redis-server.conf",
     "lib/bone.rb",
     "lib/bone/api.rb",
     "lib/bone/cli.rb",
     "try/10_generate_try.rb",
     "try/16_http_try.rb",
     "try/20_instance_try.rb",
     "try/25_key_token_object_try.rb",
     "try/30_api_memory_try.rb",
     "try/31_api_redis_try.rb",
     "try/32_api_http_try.rb",
     "try/manual_cli.rb",
     "vendor/drydock-0.6.8/CHANGES.txt",
     "vendor/drydock-0.6.8/LICENSE.txt",
     "vendor/drydock-0.6.8/README.rdoc",
     "vendor/drydock-0.6.8/Rakefile",
     "vendor/drydock-0.6.8/bin/example",
     "vendor/drydock-0.6.8/drydock.gemspec",
     "vendor/drydock-0.6.8/lib/drydock.rb",
     "vendor/drydock-0.6.8/lib/drydock/console.rb",
     "vendor/drydock-0.6.8/lib/drydock/mixins.rb",
     "vendor/drydock-0.6.8/lib/drydock/mixins/object.rb",
     "vendor/drydock-0.6.8/lib/drydock/mixins/string.rb",
     "vendor/drydock-0.6.8/lib/drydock/screen.rb"
  ]
  s.homepage = %q{https://github.com/solutious/bone}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{bone}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A simple store for remote environment variables}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<familia>, [">= 0.6.1"])
      s.add_runtime_dependency(%q<em-http-request>, [">= 0"])
    else
      s.add_dependency(%q<familia>, [">= 0.6.1"])
      s.add_dependency(%q<em-http-request>, [">= 0"])
    end
  else
    s.add_dependency(%q<familia>, [">= 0.6.1"])
    s.add_dependency(%q<em-http-request>, [">= 0"])
  end
end

